### ISSUE TITLE
Is there an option to turn off the dynamic fields option (DynamicFieldsMixin) even when passing the query?

### ISSUE THREAD

**Issue by daidaitaotao** [yezyilomo/django-restql#121]
We recently run into a situation that the children serializer break inside the to_representation method.
For example
```
class ParentSerializer(DynamicFieldsMixin, serializer.ModelSerializer):
    ...
    def to_representation(self, instance):
        representation = super().to_representation(instance)
        # Manually set the representation here. Imagine that we need to do some extra work that can't be put
        # into a serializer method field for some reason.
        # Because we pass `self.context`, any restql querying is using the parent query fields, so those fields
        # might not exist on the child, which raises a parser error.
        representation["children"] = ChildSerializer(data=instance.child, context=self.context)
class ChildSerializer(DynamicFieldsMixin, serializers.ModelSerializer)
```
As a result, ChildSerializer did not work because it did not pass correct data in the `query` params which were for the parent serializer. I wonder if we have an option to toggle dynamic field functionality when instantiating the serializer?

Thanks, 
Tao

**Comment by yezyilomo** [comment]
>  I wonder if we have an option to toggle dynamic field functionality when instantiating the serializer?


You can remove `DynamicFieldsMixin` on your `ChildSerializer` if you don't want fields filtering to apply on a child serializer.

**Comment by tredzko** [comment]
@yezyilomo What if there are other places where the `ChildSerializer` might be used with dynamic fields? Could we add an argument, like `use_dynamic_fields` that could be passed into the instance and checked?

**Comment by yezyilomo** [comment]
> @yezyilomo What if there are other places where the `ChildSerializer` might be used with dynamic fields? Could we add an argument, like `use_dynamic_fields` that could be passed into the instance and checked?

I see your point, this could be very useful, though I wouldn't suggest a name of the argument to be `use_dynamic_fields` because that's implied when inheriting `DynamicFieldsMixin`, I think it should be something like `disable_*`, I can't find a good word to put on *.

**Comment by tredzko** [comment]
@yezyilomo `disable_dynamic_fields`? 😉

**Comment by daidaitaotao** [comment]
I like the idea, can we make it happen?

**Comment by yezyilomo** [comment]
> @yezyilomo `disable_dynamic_fields`?

Kinda long but very descriptive, I think we can go with that. @daidaitaotao what's your opinion on this?

**Comment by yezyilomo** [comment]
> I like the idea, can we make it happen?

Definitely, we are going to implement it.

**Comment by daidaitaotao** [comment]
yeah `disable_dynamic_fields` sounds good, or we can have `enable_dynamic_fields` with the default value `True` and then only do `enable_dynamic_fields = False` when needed. But I am good with `disable_dynamic_fields` too. Thanks.

**Comment by yezyilomo** [comment]
> But I am good with `disable_dynamic_fields` too.

Okay, `disable_dynamic_fields` it is.

**Comment by tredzko** [comment]
This could also just be `dynamic_fields` and we could pass in a boolean (default to `True`) if we wanted to shorten it.

**Comment by yezyilomo** [comment]
> This could also just be `dynamic_fields` and we could pass in a boolean (default to `True`) if we wanted to shorten it.

I think 'disable_dynamic_fields` makes more sense and it's easy to predict that it's a boolean kwarg unlike `dynamic_fields`
