### ISSUE TITLE
How to make a mutilple viewset query ?

### ISSUE THREAD

**Issue by lyroge** [yezyilomo/django-restql#124]
How to make a mutilple viewset query ?

**Comment by yezyilomo** [comment]
Currently **Django RESTQL** does not support this, but if you have any ideas on how we can implement it you are very welcome to contribute.

**Comment by lyroge** [comment]
> Currently **Django RESTQL** does not support this, but if you have any ideas on how we can implement it you are very welcome to contribute.

ok

**Comment by tredzko** [comment]
@lyroge Just to be clear, are you talking about using one serializer or using multiple serializers in a view? Are you building out the return value manually in the view and skipping the serializer?

**Comment by tredzko** [comment]
Closing this issue. This might be a possible feature in the future, but we'd need to iron out how we should support it and scope of how useful it might be.
