### ISSUE TITLE
Nested File Field

### ISSUE THREAD

**Issue by neilfrndes** [yezyilomo/django-restql#125]
Is there a recommended method to work with a FileField in a nested serializer ?

In this example:
```
class Customer:
    signature = FileField()
    name = CharField()

class Ticket:
    customer = Customer()
    amount = FloatField()
    date = DateField()
    ...
```
How would a Ticket POST request containing a customer signature be handled?

**Comment by yezyilomo** [comment]
This has something to do with form data Content-Type, `multipart/form-data` content type does not allow sending nested fields, `application/json` content-type allow sending nested fields(of JSON string type) but not files, if you want to send files using `application/json` content-type you have to encode it to Base64 string at the expense of increasing the data size and add processing overhead in both the server and the client for encoding/decoding. So in this case you have to send two requests, First send a request to create a customer and then send the one to create a Ticket using the customer you created. i.e

`POST  /customer/`
`Content-Type: multipart/form-data`
```
{
    name: "neilfrndes",
    signature: file_with_signature
}
```

`POST  /ticket/`
`Content-Type: application/json`
```js
{
    date: "2020-01-01",
    amount: 250,
    customer: id_of_the_customer_you_created
}
```

**Comment by yezyilomo** [comment]
File uploads are generally complicated(especially when they are nested), even in GraphQL APIs it's recommended to consider switching back to REST when uploading files.

**Comment by neilfrndes** [comment]
Appreciate the the detailed answer, Thank you for this useful library!
