### ISSUE TITLE
Hyphens in query filters return an error

### ISSUE THREAD

**Issue by neilfrndes** [yezyilomo/django-restql#135]
I receive the following error when I filter a field using a phrase that contains hyphens in it:
`[
    "QuerySyntaxError: expecting '{' on (key:splash-screen){"
]`

The query I used is the following:
`https://domain.com/api/data/?query=(key:splash-screen){*}`

When I replace the hyphen with an underscore, the query runs fine. This query does not return any error:
`https://domain.com/api/data/?query=(key:splash_screen){*}`

The filter used for the "key" field is icontains (case insensitive contains).

**Comment by yezyilomo** [comment]
Hey @neilfrndes Thanks for reporting this, now you can download v0.8.3 which contain the fix.
