### ISSUE TITLE
Link bug in docs

### ISSUE THREAD

**Issue by resurrexi** [yezyilomo/django-restql#161]
I just wanted to say that I discovered your package recently and I'm absolutely blown away with what it can do. I was actually thinking of switching from drf to graphene until I found your repo. I'm so impressed I actually want to donate to your project.

Anyways, aside from my impressions, I was looking through your docs and found one minor bug in a section under the Settings tab: https://django-restql.yezyilomo.com/settings/#default_base_filter_backend

In that section, there is a dead link, **Filtering with query arguments**. I believe that link should point to http://django-restql.yezyilomo.com/querying_data/#filtering-with-query-arguments

I can fix the bug and submit a PR if you want.

**Comment by yezyilomo** [comment]
Thank you @resurrexi am glad to hear this package is helping you, it means a lot to me, I also appreciate you going through the docs to find that bug, I'll gladly accept a PR for fixing that. I have also set up a sponsor button for donating, you can go ahead and use it.

**Comment by resurrexi** [comment]
Great!

PR submitted #162

**Comment by resurrexi** [comment]
I tried to used your funding link but I got this message on the checkout:

> We aren't able to process your payment using your PayPal account at this time. Please go back to merchant and try using a different payment method.

I'm not sure if this error is because of my account or your account. Do you perhaps have a paypal.me link that I could try?

**Comment by yezyilomo** [comment]
> I'm not sure if this error is because of my account or your account. Do you perhaps have a paypal.me link that I could try?

I think it might be on my account, I just checked am currently in a country where PayPal.Me is not available. Maybe I should try stripe.

**Comment by yezyilomo** [comment]
Didn't activate this one on my paypal account "Allow payments sent to me in a currency I do not hold", I just did. try again and let me know if the problem persist.

**Comment by resurrexi** [comment]
I still can't send. :crying_cat_face:

Do you have patreon available in your country?

**Comment by yezyilomo** [comment]
I think petreon is available, I've already added a link on a sponsor button, try it.

**Comment by resurrexi** [comment]
It works!

**Comment by yezyilomo** [comment]
Thank you, I've received it.
