### ISSUE TITLE
Exploring Endpoints 

### ISSUE THREAD

**Issue by king-11** [yezyilomo/django-restql#177]

**Comment by king-11** [comment]
Is there something like swagger or graphene then we can use to explore the newly created endpoints?

**Comment by yezyilomo** [comment]
Django RestQL doesn't create new endpoints, you can browse your API through the interface provided by django rest framework itself. If you need something like Swagger check https://www.django-rest-framework.org/topics/documenting-your-api/#generating-documentation-from-openapi-schemas.

**Comment by king-11** [comment]
Actually, with swagger, I can test by rest APIs easily but with djang0-restql I have to use postman like clients to check if there is some issue with permissions or authentication so I was looking for an easier method to test the graphql endpoints created using Django-restql.
