### ISSUE TITLE
use django-restql in api_view

### ISSUE THREAD

**Issue by 3lf** [yezyilomo/django-restql#205]
how can I use django-restql in api_view?
for example:
```
@api_view()
def getInputCartWithCartJidView(request, cart_jid):
    InputCarts = InputCart.objects.get(cart_jid=cart_jid)
    return Response({"status": "success",
                     "data": InputCartSerializer(obj).data},
                    status=status.HTTP_200_OK)
```

**Comment by 3lf** [comment]
I found it after hours read code :|
just need add 
`,context={'request': request,}`
to serializer

for example:
change 
`InputCartSerializer(obj).data
`
to
`InputCartSerializer(obj,context={'request': request,}).data
`

**Comment by yezyilomo** [comment]
> I found it after hours read code :|
> just need add
> `,context={'request': request,}`
> to serializer
> 
> for example:
> change
> `InputCartSerializer(obj).data `
> to
> `InputCartSerializer(obj,context={'request': request,}).data `

Yes `DynamicFieldsMixin` needs request to work, so passing request to the context is all you need in your serializer.
