### ISSUE TITLE
Constraint error after a validation from model

### ISSUE THREAD

**Issue by alepn** [yezyilomo/django-restql#215]
After a validation from model (ex.: unique field violate), I cannot send the request again. 

It causes a constraint error:

null value in column "foo_id" violates not-null constraint

**Comment by yezyilomo** [comment]
It’s hard to know what might be causing that problem if you don’t post a piece of code which you think it might be causing that error, so please do.

**Comment by alepn** [comment]
## MODELS ##
class Profile(models.Model):
    name = models.CharField('Name', max_length=80)

class Email(models.Model):
    profile = models.ForeignKey(Profile)
    email = models.CharField('Email', max_length=80, unique=True)
## MODELS ##

## SERIALIZERS ##
from django_restql.mixins import DynamicFieldsMixin
from django_restql.serializers import NestedModelSerializer

class EmailSerializer(DynamicFieldsMixin, NestedModelSerializer):
    email_set = NestedField(EmailSerializer, many=True, required=False, allow_null=True)
    class Meta:
        model = Email
        fields = ['profile','email']

class ProfileSerializer(DynamicFieldsMixin, NestedModelSerializer):
    email_set = NestedField(EmailSerializer, many=True, required=False, allow_null=True)
    class Meta:
        model = Email
        fields = ['name','email_set']
## SERIALIZERS ##

If you send a request with a existing email, it will fail because the unique constraint.
If you resend the request with another e-mail, it show a fk constraint error, because profile_id on nested email_set is was lost.

**Comment by yezyilomo** [comment]
This is not `django-restql`'s problem, DRF doesn't handle all `IntegrityError`s raised by django ORM due to failed database constrains, so you are supposed to handle these yourself by using fields validation on your serializers, the way you did it [here](https://github.com/yezyilomo/django-restql/issues/214#issuecomment-841220640)
