### ISSUE TITLE
Problem when creating/updating ManyToOne nested field if a serializer is using fields = '__all__' 

### ISSUE THREAD

**Issue by farasu** [yezyilomo/django-restql#254]
when try to create nested record; show this error `Field name `_` is not valid for model `ModelName`.`

**Comment by yezyilomo** [comment]
Let’s see a serializer for the model which gives error.

**Comment by farasu** [comment]
`class AddressSerializer(ModelSerializer):
    class Meta:
        model = Address
        fields = '__all__'
class EducationSerializer(ModelSerializer):
    class Meta:
        model = Education
        fields = '__all__'
        # exclude = ['created_at', 'updated_at']


class ExprienceSerializer(ModelSerializer):
    class Meta:
        model = Exprience
        fields = '__all__'
        # exclude = ['created_at', 'updated_at']

    

class EmployeeSerializer(ModelSerializer):
    address = NestedField(AddressSerializer, many=True)
    education = NestedField(EducationSerializer, many=True)
    exprience = ExprienceSerializer(many=True)

    class Meta:
            model = Employee
            fields = '__all__'`

**Comment by farasu** [comment]
`class AddressSerializer(ModelSerializer):
    class Meta:
        model = Address
        fields = '__all__'`

`class EducationSerializer(ModelSerializer):
    class Meta:
        model = Education
        fields = '__all__'`

`class ExprienceSerializer(ModelSerializer):
    class Meta:
        model = Exprience
        fields = '__all__'`

`class EmployeeSerializer(NestedModelSerializer):
    address = NestedField(AddressSerializer, many=True)
    education = NestedField(EducationSerializer, many=True)
    exprience = ExprienceSerializer(many=True)`
`
    class Meta:
            model = Employee
            fields = '__all__'
`

**Comment by farasu** [comment]
```
class AddressSerializer(ModelSerializer):
     class Meta:
        model = Address
        fields = '__all__'
```

```
class EducationSerializer(ModelSerializer):
    class Meta:
        model = Education
        fields = '__all__'
```

```
class ExprienceSerializer(ModelSerializer):
    class Meta:
        model = Exprience
        fields = '__all__'
```

```
class EmployeeSerializer(NestedModelSerializer):
    address = NestedField(AddressSerializer, many=True)
    education = NestedField(EducationSerializer, many=True)
    exprience = ExprienceSerializer(many=True)

    class Meta:
            model = Employee
            fields = '__all__'
```

**Comment by yezyilomo** [comment]
All serializers seems okay, now can I see json data which you're sending when creating `Employee`.

**Comment by farasu** [comment]
```
{
        "address": {
            "create":[
            {
                "current": true,
                "province": "Kabul",
                "district": "5 District",
                "area": "Gullae"
            },
            {
                "current": true,
                "province": "Kabul",
                "district": "5 District",
                "area": "Gullae"
            }
        ]
        },
        "education":{
            "create":  [
            {
                "education_level": "master",
                "education_field": "Computer Scince",
                "university": "Rana",
                "start_date": "2021-08-03",
                "end_date": "2021-08-03"
            },
            {
                "education_level": "master",
                "education_field": "Computer Scince",
                "university": "Rana",
                "start_date": "2021-08-03",
                "end_date": "2021-08-03"
            }
        ]
        },
        "exprience": {
            "create": [
            {
                "position": "IT Manager",
                "sallary": 2000,
                "id_card": "IT-97867",
                "start_date": "2021-08-03",
                "end_date": "2021-08-03"
            }
        ]
        },
        "name": "Farasu",
        "lname": "farasu",
        "fname": "farasu",
        "age": "2021-08-03",
        "gender": "male",
        "marital_state": "single",
        "phone": "0775731593",
        "email": "farasu@gamil.com",
        "identity_no": "1399-0600-87943",
        "employee_type": "doctor",
        "status": true
    }
````
`

**Comment by sommelon** [comment]
I looked into it and I found that in ModelSerializer on line [1041](https://github.com/encode/django-rest-framework/blob/98e56e0327596db352b35fa3b3dc8355dc9bd030/rest_framework/serializers.py#L1041) the value of field_names is `['_', '_', 'a', 'l', 'l', '_', '_']`. So the `fields='__all__'` gets converted to a list somewhere.

**Comment by yezyilomo** [comment]
> ```
> {
>         "address": {
>             "create":[
>             {
>                 "current": true,
>                 "province": "Kabul",
>                 "district": "5 District",
>                 "area": "Gullae"
>             },
>             {
>                 "current": true,
>                 "province": "Kabul",
>                 "district": "5 District",
>                 "area": "Gullae"
>             }
>         ]
>         },
>         "education":{
>             "create":  [
>             {
>                 "education_level": "master",
>                 "education_field": "Computer Scince",
>                 "university": "Rana",
>                 "start_date": "2021-08-03",
>                 "end_date": "2021-08-03"
>             },
>             {
>                 "education_level": "master",
>                 "education_field": "Computer Scince",
>                 "university": "Rana",
>                 "start_date": "2021-08-03",
>                 "end_date": "2021-08-03"
>             }
>         ]
>         },
>         "exprience": {
>             "create": [
>             {
>                 "position": "IT Manager",
>                 "sallary": 2000,
>                 "id_card": "IT-97867",
>                 "start_date": "2021-08-03",
>                 "end_date": "2021-08-03"
>             }
>         ]
>         },
>         "name": "Farasu",
>         "lname": "farasu",
>         "fname": "farasu",
>         "age": "2021-08-03",
>         "gender": "male",
>         "marital_state": "single",
>         "phone": "0770000000",
>         "email": "farasu@gamil.com",
>         "identity_no": "1000-230-4567",
>         "employee_type": "doctor",
>         "status": true
>     }
> ```
> 
> 
>      
>   
> 
> `

This looks okay too, but am still not able to reproduce it, maybe it’s a version specific bug, I’ve tried to use ‘__all__’ in fields but still it’s running just fine.

**Comment by yezyilomo** [comment]
> I looked into it and I found that in `ModelSerializer` on line [1041](https://github.com/encode/django-rest-framework/blob/98e56e0327596db352b35fa3b3dc8355dc9bd030/rest_framework/serializers.py#L1041) the value of `field_names` is `['_', '_', 'a', 'l', 'l', '_', '_']`. So the `fields='__all__'` string gets converted to a list somewhere in the code.

This could probably be the cause, have you managed to reproduce it?.

**Comment by sommelon** [comment]
Yes, but I'm not exactly sure why it's happening. I've tried reproducing [this](https://github.com/yezyilomo/django-restql/issues/211#issuecomment-892844733) issue and I've got this error:

```
    File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 419, in run_validation
    value = self.to_internal_value(data)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\django_restql\mixins.py", line 546, in to_internal_value
    validated_data = super().to_internal_value(data)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 476, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 607, in run_validation
    value = self.to_internal_value(data)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\django_restql\fields.py", line 215, in to_internal_value
    return self.data_for_create(data)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\django_restql\fields.py", line 171, in data_for_create
    validation_methods[operation](values)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\django_restql\fields.py", line 138, in validate_create_list
    return self.validate_data_list(data)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\django_restql\fields.py", line 120, in validate_data_list
    parent_serializer.is_valid(raise_exception=True)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 725, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 607, in run_validation
    value = self.to_internal_value(data)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 643, in to_internal_value
    validated = self.child.run_validation(item)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 419, in run_validation
    value = self.to_internal_value(data)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 472, in to_internal_value
    for field in fields:
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 355, in _writable_fields
    for field in self.fields.values():
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 349, in fields
    for key, value in self.get_fields().items():
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 1054, in get_fields
    source, info, model, depth
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 1199, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "e:\Documents\Work\blablabla\backend\.venv\lib\site-packages\rest_framework\serializers.py", line 1319, in build_unknown_field
    (field_name, model_class.__name__)
django.core.exceptions.ImproperlyConfigured: Field name `_` is not valid for model `Milestone`.
```

**Comment by yezyilomo** [comment]
Thank you @sommelon for posting the whole error trace back, I think the part causing it is https://github.com/yezyilomo/django-restql/blob/273ef585f0312921fae1b381951fa7ae9f58bde9/django_restql/fields.py#L120-L122
We forgot to handle a case where the value of  `serializer_class.Meta.fields` is `__all__`, so it’s definitely a bug.

**Comment by sommelon** [comment]
No problem.
I think some Issue templates with guidelines would be great so that people know what information to provide.

**Comment by yezyilomo** [comment]
> No problem.
> I think some Issue templates with guidelines would be great so that people know what information to provide.

Yeah, I’ll work on it, if you have an idea of how issue template should look like for this project feel free to open an issue about it, I’ll appreciate the help.

**Comment by sommelon** [comment]
@yezyilomo I've created the issue #256
