### ISSUE TITLE
Runtests is failing.

### ISSUE THREAD

**Issue by gonzaloamadio** [yezyilomo/django-restql#255]
* I have cloned the package. 
* Create a venv (_python 3.7_). 
* Install requirements (_pip install -r requirements.txt_). 
* Install package (_pip install django-restql_)

But when trying to execute tests I have the following error:

```django.core.exceptions.ImproperlyConfigured: Cannot import 'testapp'. Check that 'tests.testapp.apps.TestappConfig.name' is correct.```

**Comment by yezyilomo** [comment]
Use Django<3.2, app config in Django was changed in version 3.2, we have not migrated to the new way of configuring app yet. Note that’s for tests only but as for support, django-restql works with version 3.2 too..

**Comment by gonzaloamadio** [comment]
Worked

**Comment by yezyilomo** [comment]
> Use Django<3.2, app config in Django was changed in version 3.2, we have not migrated to the new way of configuring app yet. Note that’s for tests only but as for support, django-restql works with version 3.2 too..

Now tests can run on v3.2 too.
