### ISSUE TITLE
Add REPLACE operation proposal

### ISSUE THREAD

**Issue by gonzaloamadio** [yezyilomo/django-restql#260]
Hi, sorry if I am posting in the wrong place. It is not an issue but more a proposal.

I would like to propose a new operation. REPLACE.

The scenario we have is that we have a model with a FK to another model.

```
class ModelA(models.Model):
  .. some fields

class Person(models.Model):
   model_a = FK(ModelA)
  .. persons fields
```

And we would like to replace the hole persons_set related to ModelA at once. Right know, we would have to track the original set of persons, and then add and remove a list of IDs to achieve a hole replacement of the set.

Would you like the idea of adding this operation? @yezyilomo

**Comment by yezyilomo** [comment]
I think it's good to keep operations simple, one operation should do one thing, but REPLACE operation seems like REMOVE + ADD which makes it not simple.

I think the hardest  part on your scenario is to track the original set of persons and add them to REMOVE list, Now what if there was a way to remove all related items(original persons_set in your case) without passing their ids, something like `{"remove":  "__all__"}`,  With this your case could simply be solved as 

```js
{
    "add":  [3, 5, 6, ..]
    "remove":  "__all__"
}
```
No need to track the original set of persons to add them to REMOVE list, just say you want the whole persons_set removed by using `__all__` directive. The good thing is about this approach is that we won't need to add a new operator instead we empower users to create complex operations like REPLACE and others for themselves.

As per our example you can see that we have empowered user to create REPLACE operator for themselves by combining the power of ADD and REMOVE operator.

It's just an idea.

**Comment by sommelon** [comment]
> I think it's good to keep operations simple, one operation should do one thing, but REPLACE operation seems like REMOVE + ADD which makes it not simple.
> 
> Correct me if am wrong, I think the hardest part on your scenario is to track the original set of persons and add them to REMOVE list, But what if there was a way to remove all related items(original persons_set in your case) without needing to pass their ids, something like `{"remove": "__all__"}`, With this your case could simply be solved as
> 
> ```js
> {
>     "add":  [3, 5, 6, ..]
>     "remove":  "__all__"
> }
> ```
> 
> No need to track the original set of persons to add them to REMOVE list, just say you want the whole persons_set removed by using `__all__` directive. The good thing about this approach is that we won't need to define a new operator instead we empower users to create complex operations like REPLACE and others for themselves.
> 
> As per our example you can see that we have empowered user to create REPLACE operator for themselves by combining the power of ADD and REMOVE operator.
> 
> ### It's just an idea.

One question I would have about your proposition is: In what order would the operations be applied? In the order of specification? Or would `remove` be always applied first?

**Comment by yezyilomo** [comment]
> This would be better because you could either create or add objects while removing the old ones.
> One question I would have about your proposition is: In what order would the operations be applied? In the order of specification? Or would `remove` be always applied first?

Sorry I meant to write 
```js
{
    "remove":  "__all__",
    "add":  [3, 5, 6, ..]
}
```
The order of operations matters, it has always been that way.

**Comment by gonzaloamadio** [comment]
Your time response is awesome! Great, great idea. This works great!
Should be added to documentation as well when possible for future users =)

**Comment by yezyilomo** [comment]
> Your time response is awesome! Great, great idea. This works great!
> Should be added to documentation as well when possible for future users =)

We have to add it to documentation before releasing v0.14.0, just started working on it, I think it’ll be ready by tomorrow if not today.
