### ISSUE TITLE
avoid requesting unnecessary data in SQL

### ISSUE THREAD

**Issue by jsmedmar** [yezyilomo/django-restql#27]
Something that I really like about drf-dynamic-fields  is that they simplify the SQL query, if you are just asking for `fields=pk` then the SQL avoids making prefetched queries. Wondering if this could be added to django-restql.

**Comment by yezyilomo** [comment]
Thanks for taking your time to check this project. This seems like a good idea for improving performance, I haven't found a way to implement that yet so if you have any idea which can help you are very welcome to contribute.

**Comment by joseph-vedadi** [comment]
So this would not improve any performance.
If I have a huge nested data, and I only need top level, will it still fetch the full data ???

**Comment by tredzko** [comment]
Just popping in, this is being addressed by #67, which hopefully will help with your use case.
