### ISSUE TITLE
Optional GenericRel support

### ISSUE THREAD

**Issue by shinneider-musa** [yezyilomo/django-restql#322]
Hi, the new version (0.16), uses `GenericRel` and `ContentType` imported in `mixins.py` lines 4 and 5, however this breaks all projects that do not use `contenttype` modules, especially for those who use django as microservices... removing all django stuff (auth, contenttype, messages and etc)...

**Comment by yezyilomo** [comment]
Thank you for reporting this, You are right, I'm working on fixing this..

**Comment by shinneider-musa** [comment]
@yezyilomo just on thing, in code you put a Exception for `ImportError` however the django raises a `RuntimeError`
<img width="995" alt="image" src="https://github.com/user-attachments/assets/b46ad04a-f7d4-4550-bead-0714c8822b7f" />
