### ISSUE TITLE
Support prefetching and selecting related fields dynamically according to a query parameter

### ISSUE THREAD

**Issue by tredzko** [yezyilomo/django-restql#63]
Hey there!

Have started recently using the project and super impressed! Very helpful to be able to narrow down the fields returned on the fly.

One consideration my team and I had was about trying to properly `prefetch_related`/`select_related` when we are or are not including fields. For example, if a `Course` has `books`, but we only ask for `id`, then we should not prefetch books. But if we do include books, we definitely want to prefetch them to prevent the list queries from getting out of control.

We have made our own internal implementation and mixin, but wanted to gauge interest and make sure we take any cases we haven't run into yet into consideration. Thoughts?

**Comment by yezyilomo** [comment]
I thought about using `prefetch_related` and `select_related` automatically too but then I saw this issue [ #1964](https://github.com/encode/django-rest-framework/issues/1964), though I think this guy has a point https://github.com/encode/django-rest-framework/issues/1964#issuecomment-59645915. am open to any ideas on this and I would love to see your implementation.

**Comment by tredzko** [comment]
The implementation we have is basically a view-level (with a possibility for serializer level, though not sure we're gonna keep it as we test) explicit mapping of field names to `prefetch_related` strings/Prefetch objects and `select_related` strings. Trying to automatically handle prefetching or joining is probably too ambitious and has too many edge cases I think.

**Comment by yezyilomo** [comment]
You are right, I also think the decision of whether to use `prefetch_related` and `select_related` should be left to library users because they are the ones who knows when and where to improve performance, so am closing this.

**Comment by tredzko** [comment]
@yezyilomo I just mean that we could provide a means to define prefetching and selecting based on the restql query passed in. That's pretty feasible with a view mixin and defined structure.

**Comment by yezyilomo** [comment]
Ooh, that could work but API consumer shouldn't bother about stuffs like that and using that feature would require a person who understands how the back-end works which in most cases is not. Also doing that would mean leaving the issue of performance to API consumers which I think is not a good thing.

**Comment by tredzko** [comment]
It's for the backend. The definition of the `select_related` or `prefetch_related` calls would be entirely based on what the client passed in, but explicitly defined by whoever maintains the api. This allows further gains from a performance perspective, since we can turn on `prefetch_related`/`select_related` without worrying about doing those if they aren't needed (gaining back the latency and cpu overhead of doing it otherwise).

For example, the course serializer could look something like this:
```python
class CourseViewSet(RestQLViewMixin, viewsets.ModelViewSet):
    serializer_class = CourseSerializer
    queryset = Course.objects.all()
    restql_orm_mapping = {
        "prefetch": {
            "books": "books"
        }
    }

    def get_queryset(self):
        queryset = super().get_queryset()

        # Mixin would provide easy access to restql query.
        if self.restql_query is not None:
            # Apply our prefetching via the mapping.
            queryset = self.get_restql_queryset(queryset)
        return queryset
```

With the above example, `prefetch_related("books")` is applied if `books` is an included field. Otherwise, we skip that prefetching (for example, if we query only for course name).

This would be optional of course, but would help those who are at scale where this form of optimization is employed and would translate to significant gains in some places.

If there is interest, I can get a PR with our solution up for review to see if it would be of benefit to the project.

**Comment by yezyilomo** [comment]
Ooh I think I've got your point, So you mean just like we have improved performance by providing a way to select fields dynamically, we could also provide a way to `prefetch_related` and `select_related` dynamically so that we don't prefetch or select related fields for a field which is not included on a query, right?.

**Comment by tredzko** [comment]
@yezyilomo Right! We ran into an issue where we were prefetching and using select_related for fields we were no longer returning, so we figured we'd map what we need to prefetch or join for explicitly to dynamically build that part out. 🙂

**Comment by yezyilomo** [comment]
Okay, you know at first I thought it was about using `prefetch_related` and `select_related` automatically, now that I understand I think it's a very great idea and thanks for bringing that up.

**Comment by yezyilomo** [comment]
You know now I see how close the idea of selecting fields dynamically is related to the idea of dynamically prefetching and selecting related fields. I look forward reviewing your PR.

**Comment by yezyilomo** [comment]
Oooh and shouldn't we rename the issue to "Support prefetching and selecting related fields dynamically according to query parameter"? I find this easier to understand than " Open
View ORM Definitions Based On Query", I don't know if it's just me, what do you think?.

**Comment by tredzko** [comment]
@yezyilomo I agree, that's a much better issue title.
