### ISSUE TITLE
DynamicSerializerMethodField no parent nested_fields when no query passed in.

### ISSUE THREAD

**Issue by jheld** [yezyilomo/django-restql#76]
When `query` is not passed in, but the `DynamicSerializerMethodField` is  used, the `self.parent.nested_fields` fails because `nested_fields` wasn't set.

When `query` is passed in, it works.

**Comment by tredzko** [comment]
I'll take a look into this. @yezyilomo Could you mark me as an assignee, or could I get privileges for the repo so I can handle some of this for you?
