### ISSUE TITLE
Toggle automatic application on EagerLoadingMixin

### ISSUE THREAD

**Issue by tredzko** [yezyilomo/django-restql#85]
We have a few cases where we might not want to apply the `EagerLoadingMixin` `get_queryset` by default. For example, we might have our own prefetching/joining we want to do when someone doesn't send in a `query`. Currently, the mixin will return a query result even if a user did not send one in and will then apply the prefetching and joining specified on the view.

I'm imagining this as a boolean field on the mixin, such as `auto_apply_eager_loading` or some equivalent, and that field would be checked in the overridden `get_queryset` before attempting to apply it.

**Comment by yezyilomo** [comment]
> Currently, the mixin will return a query result even if a user did not send one in and will then apply the prefetching and joining specified on the view.

Yeah because if you don't send a query it means you want to get all fields and that is exactly what 's happening if you send your request without a query parameter, u get all the fields,  so the query passed to the eager loading mixin in this case will be
```
        query = {
            "include": ["*"],
            "exclude": []
        }
```
which is right because you want to get all fields.

**Comment by tredzko** [comment]
Correct, we may want all fields, but the user didn't use `restql` to ask for it. We also may do extra work with our queryset, so calling `super().get_queryset()` in our view will *always* apply our eager loading, even if we have a different case if the user decided not to pass that in (or maybe passes in another query param where we want to switch how we get our data or what serializer we want to use for some reason)

**Comment by yezyilomo** [comment]
> Correct, we may want all fields, but the user didn't use restql to ask for it. We also may do extra work with our queryset, so calling `super().get_queryset()` in our view will _always_ apply our eager loading, even if we have a different case if the user decided not to pass that in (or maybe passes in another query param where we want to switch how we get our data or what serializer we want to use for some reason)


So what you mean is that we should apply eager loading mixin only if the user sends a request with a query parameter, and if the request has no query parameter  we should at least give control to specify whether to apply eager loading mixin or not, right?

**Comment by tredzko** [comment]
@yezyilomo Yeah, or just empower the user to toggle that functionality. #87 shows what I'm suggesting along with docs. Not too big of a change. 🙂
