### ISSUE TITLE
Provide way to check if a user passed in a query to EagerLoadingMixin

### ISSUE THREAD

**Issue by tredzko** [yezyilomo/django-restql#86]
We have a few cases where if a user does not use restql, we want to apply different workflows to our querysets, so a builtin property would be incredibly useful for that since `parsed_query` no longer can be `None` as a tell for it.

**Comment by yezyilomo** [comment]
Oooh you mean like the way we provided a way to pass a query to `DynamicFieldMixin` in case you don't want to use the one from the request?. This could be useful.

**Comment by tredzko** [comment]
More for being able to tell if the user passed in `query` or not. If someone who uses the mixin wants to send their own query in the case through, then yeah. I'll be making a PR to show what I mean in a moment.

**Comment by yezyilomo** [comment]
Hey @tredzko I just realized this idea #84 enable making `EagerLoadingMixin` independent of `DynamicFieldsMixin` which means `EagerLoadingMixin` will have its own `has_query_param` method since it's inheriting `RequestQueryParserMixin`, just check this PR #89

**Comment by tredzko** [comment]
@yezyilomo I like that idea. It doesn't make a ton of sense to change it by serializer in practice, since now you'd then need to know the queryparam to use *per instance*.
