### ISSUE TITLE
Prefetch is not iterable error on EagerLoadingMixin

### ISSUE THREAD

**Issue by tredzko** [yezyilomo/django-restql#93]
When specifying a `Prefetch` on a mapping field, but not putting it in a list, it raises a not iterable error.

[The line that raises this error](https://github.com/yezyilomo/django-restql/blob/1e53ce232cc87e8a7c2c16ed06629fe2af2ca37d/django_restql/mixins.py#L357) is only checking for `str` instances, but should also check for `Prefetch` instances. 

Here is an example syntax that causes the issue:

```py
prefetch_related = {
    "tomes": Prefetch("books", queryset=Book.objects.all())
}
```

**Comment by yezyilomo** [comment]
Actually I didn't handle a case of using `Prefetch` object at all, and if you are making a PR please add two tests, one using a list of prefetch objects and the other using a plain prefetch object.
